# Generated by Django 2.2.3 on 2019-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('submenu', models.CharField(default='0', max_length=1, verbose_name='是否有子菜单')),
                ('parentmenu', models.CharField(max_length=50, verbose_name='父菜单')),
                ('url', models.CharField(max_length=50, verbose_name='菜单链接地址')),
                ('icon', models.CharField(blank=True, max_length=16, null=True, verbose_name='菜单图标')),
                ('seq', models.CharField(max_length=4, verbose_name='排序')),
            ],
            options={
                'verbose_name': '系统菜单',
                'verbose_name_plural': '系统菜单',
            },
        ),
    ]
