# Generated by Django 2.2.3 on 2019-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mjtype', models.CharField(choices=[('wg', 'KW控制板系列'), ('ZK', '门禁一体机系列'), ('bl', '云门禁系列')], default='wg', max_length=20, verbose_name='控制器系列')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备序列号')),
                ('ip', models.CharField(max_length=50, verbose_name='设备IP')),
                ('netmask', models.CharField(max_length=50, verbose_name='子网掩码')),
                ('netgate', models.CharField(max_length=50, verbose_name='网关')),
                ('mac', models.CharField(max_length=50, verbose_name='MAC')),
                ('ver', models.CharField(default='', max_length=50, verbose_name='硬件版本')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
